name: Windforecast
channels:
 - conda-forge
dependencies:
 - spyder
 - python>=3.10,<3.13
 - numpy<2.1
 - pandas
 - scipy
 - matplotlib
 - statsmodels
 - scienceplots
 - seaborn
 - properscoring
 - r
 - r-quantreg
 - r-readr
 - pip
 - pip:
   - tensorflow
   - tensorflow-probability
   - nabqr
