name: Thesis
channels:
 - conda-forge
dependencies:
 - python
 - numpy
 - spyder
 - pandas
 - scipy
 - matplotlib
 - statsmodels
 - scienceplots
 - seaborn
 - properscoring
 - spyder
 - tqdm
 - pytorch
 - keras
 - r
 - r-quantreg
 - r-readr
 - miktex
 - pip
 - pip:
   - -e ../nabqra
   - -e ../nabqr
variables:
  MATPLOTLIBRC: C:\Users\kpfs\Projects\Windpower-Correlation-Structure\Settings
#after creation/update the r package "onlineforecast" need to be install through r