low_value = 0.01

Zones = ["DK1-offshore", "DK1-onshore", "DK2-offshore", "DK2-onshore"]

[Zone-Limits]
"DK1-offshore" = [0,1250]
"DK1-onshore" = [0,3600]
"DK2-offshore" = [0,1000]
"DK2-onshore" = [0,650]